### ISSUE TITLE
Add option to allow or deny file access from configuration

### ISSUE THREAD

**Issue by adhokshajmishra** [guptabhinav49/Process-Activity-Firewall#6]
Application firewall should be able to allow/deny/log access of any particular file given in configuration. The configuration should have following:
1. All prior configurations (file. filepath, regex etc)
2. Control policy (allow, deny, log)

In case of deny, return permission error.

**Comment by guptabhinav49** [comment]
Added the required support along with the prior configurations. Please check once ;)
